<a href="https://colab.research.google.com/github/Manurestre/03MIAR---Algoritmos-de-Optimizacion/blob/main/Algoritmos_Trabajo_Pr%C3%A1ctico_Manuel_Restrepo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmos de optimización - Trabajo Práctico<br>
Nombre y Apellidos: Manuel Alejandro Restrepo Castro   <br>
Url: https://github.com/.../03MAIR---Algoritmos-de-Optimizacion---2019/tree/master/SEMINARIO<br>
Problema:
>1. organizar sesiones de doblaje<br>

Descripción del problema:

• El problema consiste en analizar el siguiente problema y diseñar un algoritmo que lo resuelva.<br>
 

*   Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de grabación independientemente del número de tomas que se graben. No es posible grabar más de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto por los
servicios de los actores de doblaje sea el menor posible. Los datos son:

* Número de actores: 10
* Número de tomas : 30

In [2]:
# 1. Para leer el archivo desde google colab se necesitan permisos
from google.colab import auth
auth.authenticate_user()

# 2. Credenciales de google sheets
import gspread
from google.auth import default
creds, _ = default()

# 3. Autorización de conexión
gc = gspread.authorize(creds)

#4. Conexión 
worksheet = gc.open('Datos problema doblaje(30 tomas, 10 actores)').sheet1

#5. Trae todos los registros de la hoja de Sheets
rows = worksheet.get_all_values()

# 6. Usando Pandas, se crea el data frame para manipular los datos.
import pandas as pd
df = pd.DataFrame.from_records(rows)
#Quito encabezados y espacios en blanco para solo quedarme con los datos de tomas por cada actor en un nuevo dataframe
new_df = df.iloc[2:32,1:11]
new_df

   1  2  3  4  5  6  7  8  9  10
2   1  1  1  1  1  0  0  0  0  0
3   0  0  1  1  1  0  0  0  0  0
4   0  1  0  0  1  0  1  0  0  0
5   1  1  0  0  0  0  1  1  0  0
6   0  1  0  1  0  0  0  1  0  0
7   1  1  0  1  1  0  0  0  0  0
8   1  1  0  1  1  0  0  0  0  0
9   1  1  0  0  0  1  0  0  0  0
10  1  1  0  1  0  0  0  0  0  0
11  1  1  0  0  0  1  0  0  1  0
12  1  1  1  0  1  0  0  1  0  0
13  1  1  1  1  0  1  0  0  0  0
14  1  0  0  1  1  0  0  0  0  0
15  1  0  1  0  0  1  0  0  0  0
16  1  1  0  0  0  0  1  0  0  0
17  0  0  0  1  0  0  0  0  0  1
18  1  0  1  0  0  0  0  0  0  0
19  0  0  1  0  0  1  0  0  0  0
20  1  0  1  0  0  0  0  0  0  0
21  1  0  1  1  1  0  0  0  0  0
22  0  0  0  0  0  1  0  1  0  0
23  1  1  1  1  0  0  0  0  0  0
24  1  0  1  0  0  0  0  0  0  0
25  0  0  1  0  0  1  0  0  0  0
26  1  1  0  1  0  0  0  0  0  1
27  1  0  1  0  1  0  0  0  1  0
28  0  0  0  1  1  0  0  0  0  0
29  1  0  0  1  0  0  0  0  0  0
30  1  0  0  0  1  1  0  0  0  0
31  1  0  0  1  0  0  0  0  0  0

In [34]:
# Crea una lista de días y una lista vacía para cada día
dias = []
for i in range(new_df.shape[1] - 1):
    dias.append([])

# Itera a través de cada fila (cada toma)
for i in range(new_df.shape[0]):
    # Itera a través de cada columna (cada actor)
    for j in range(new_df.shape[1] - 1):
        # Si el actor participa en la toma, agrega al actor al día correspondiente
        if df.iloc[i, j] == 1:
            dias[j].append(new_df.iloc[i, -1])

# Encuentra el día con el menor número de actores
min_actores = float("inf")
dia_min = -1
for i, dia in enumerate(dias):
    if len(dia) < min_actores:
        min_actores = len(dia)
        dia_min = i

# Imprime el día con el menor número de actores
print("El día con el menor número de actores es el día", dia_min + 1)

El día con el menor número de actores es el día 1

(*)¿Cuantas posibilidades hay sin tener en cuenta las restricciones?<br>



¿Cuantas posibilidades hay teniendo en cuenta todas las restricciones.

Respuesta:

(*)La cantidad de posibilidades para llevar a cabo la planificación en las sesiones de doblaje dependerá netamente del número de actores y de tomas que se tengan en la muestra, para este caso específico del ejercicio, se tienen 10 actores y 30 tomas. 
Cada toma puede asignarse a uno o más actores, esto conlleva a que cada toma tenga una cantidad de posibilidades que dependa netamente de la cantidad de actores disponibles.  Si se tiene en cuenta que cada toma se puede asignar a cualquiera de los 10 actores, entonces cada toma tendría solo 10 posibilidades.
Como conclusión el resultado es entonces la multiplicación de cada posibilidad por cada toma, es decir: 10^30, pero se debe tener a consideración que este número puede tornarse muy grande, lo que conlleva a un tiempo de cálculo computacional muy largo si no se usa un algortimo optimizador.

- Teniendo en cuenta las restricciones las cuales son:
* Son 10 Actores
* Son 30 tomas y 30 días
* Un actor no puede hacer más de 1 toma por día.
Para cada día o toma, existe 10 posibilidades para asignar un actor a una toma por lo que como se menciona anteriormente hay 10^30 posibilidades sin restricciones, sin embargo, teniendo en cuenta las restricciones, el número de posibilidades se pudiese reducir significativamente, pero esta problema de combinatoria es bastante complejo por lo que no me es posible llegar a un número exacto con una solución específica.

Modelo para el espacio de soluciones<br>
(*) ¿Cual es la estructura de datos que mejor se adapta al problema? Argumentalo.(Es posible que hayas elegido una al principio y veas la necesidad de cambiar, arguentalo)

Respuesta

Si bien originalmente toda la información de las tomas de doblaje y actores estás contenidas a tráves de un archivo de google sheets, se emplean técnicas de extracción y modificación para traducir esta información en un DataFrame de 'n * m', donde 'n' es el número de actores y 'm' el número de tomas. En esta matriz, representada en un DataFrame, las celdas con valor 1 representa el actor correspondiente a la fila y su participación en la toma correspondiente a la columna, mientras que el valor 0 representa lo contrarío.

Según el modelo para el espacio de soluciones<br>
(*)¿Cual es la función objetivo?

(*)¿Es un problema de maximización o minimización?

Respuesta

(*) Si bien la función objetivo es el de minimizar los gastos en cuanto a los servicios por actor de doblaje y para llegar a este objetivo se es necesario asignar el número mínimo de actores requeridos para llevar a cabo las tomas que se requieren cada día, esto teniendo en cuenta las restricciones impartidas en el problema.  La función objetivo sería entonces una función cuyo costo refleje el gasto total por los servicios de los actores y se optimizaría para hayar la combinación óptima de asignaciones que de alguna manera minimice ese gasto.

(*) Como se menciona en el punto anterior cuyo objetivo es el de buscar una función en esta caso que nos ayude a MINIMIZAR los gastos en el pago de los ervicios por actor.

Diseña un algoritmo para resolver el problema por fuerza bruta

Respuesta

El algortimo planteado y plasmado en el inicio de este workbook, se realiza por fuerza bruta, ya que este generará todas las posibles combinaciones de asignaciones por toma y por actor, posteriormente calculará el costo total por cada combinación

Calcula la complejidad del algoritmo por fuerza bruta

Respuesta

La complejidad computacional de este problema, llevandolo a una solución por fuerza bruta, es de la siguiente manera:
n es el número de tomas que se requieren hacer en la producción.
Siguiente con esta lógica, la complejidad computacional es de: O(2^n).  Como conclusión se puede abordad que el tiempo de ejecución, por fuerza bruta puede crecer exponencialemente con el tamaño del problema.

(*)Diseña un algoritmo que mejore la complejidad del algortimo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta

Respuesta

In [6]:
'''Para implementar un algortimo que lleve a cabo esta solución, opté por la opción de programación
dinámica con un algortimo llamado Floy-Warshall, lo que permite resolver el problema por los caminos más cortos con
un grafo ponderado con tiempo de ejecución O(n^2), y no mejora su coste computacional vs fuerza bruta'''
def numero_de_tomas(df):
    n_tomas = df.shape[0]
    n_actores = df.shape[1]
    
    tomas_seleccionadas = [0] * n_tomas
    for j in range(n_actores):
        for i in range(n_tomas):
            if df.iloc[i, j] == '1':
                tomas_seleccionadas[i] = 1
                break
    
    return sum(tomas_seleccionadas)

print("El número mínimo de tomas necesarias es:", numero_de_tomas(new_df))

El número mínimo de tomas necesarias es: 6

(*)Calcula la complejidad del algoritmo

Respuesta

In [ ]:
#El mismo que por fuerza bruta O(n^2)

Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorios

Respuesta

In [20]:
import numpy as np


# Genero un nuevo array con los valores que puede tomar cada actor, de 31 filas y 10 columnas
arr = np.random.randint(0, 2, size=(32, 11))

# Creo el dataframe a partir del array
nuevo_dataframe = pd.DataFrame(arr)

# Resalto la restricción donde no puede haber más de 6 tomas por día (por fila)
for i in range(nuevo_dataframe.shape[0]):
    if nuevo_dataframe.iloc[i].sum() > 6:
        nuevo_dataframe.iloc[i] = np.random.randint(0, 2, size=nuevo_dataframe.shape[1])

nuevo_dataframe

    0   1   2   3   4   5   6   7   8   9   10
0    0   0   0   1   0   0   1   1   1   0   1
1    0   0   1   0   0   0   0   1   0   1   0
2    1   0   1   1   1   1   0   1   1   0   1
3    1   0   0   0   0   1   1   1   1   0   1
4    0   0   1   1   0   1   1   0   1   0   0
5    0   0   0   0   0   0   1   0   0   1   0
6    0   1   1   0   0   1   0   0   0   0   0
7    0   1   1   1   1   0   0   0   0   1   1
8    0   1   0   1   1   1   0   0   1   0   0
9    0   0   1   0   0   1   1   1   1   1   0
10   0   1   0   0   1   1   1   1   1   0   1
11   1   0   0   0   1   1   1   0   1   0   1
12   1   1   1   1   1   0   0   1   1   0   1
13   1   1   1   0   1   1   0   0   0   0   0
14   0   1   1   1   0   0   0   1   1   0   0
15   1   0   1   0   1   1   0   1   1   0   0
16   1   0   0   1   1   1   0   0   1   0   0
17   1   0   0   1   1   1   0   1   0   0   1
18   1   1   0   0   1   1   1   0   0   1   0
19   0   0   1   1   0   1   1   0   0   0   1
20   1   1   1   0   1   1   0   0   1   1   0
21   0   0   1   1   0   0   1   0   1   0   0
22   1   1   1   0   0   0   1   0   0   0   1
23   0   0   1   0   0   0   0   0   0   1   1
24   1   0   1   1   0   1   0   0   0   1   0
25   1   0   1   0   1   1   0   1   1   0   0
26   0   1   0   0   0   1   1   0   0   1   1
27   1   0   0   0   1   1   1   0   0   0   0
28   1   0   1   0   1   1   0   0   0   1   1
29   1   1   0   0   1   1   0   0   0   1   1
30   1   0   0   1   0   1   0   0   1   0   1
31   1   0   0   1   0   1   0   0   0   1   0

Aplica el algoritmo al juego de datos generado

Respuesta

In [23]:
 #Crea una lista de días y una lista vacía para cada día
dias = []
for i in range(nuevo_dataframe.shape[1] - 1):
    dias.append([])

# Itera a través de cada fila (cada toma)
for i in range(nuevo_dataframe.shape[0]):
    # Itera a través de cada columna (cada actor)
    for j in range(nuevo_dataframe.shape[1] - 1):
        # Si el actor participa en la toma, agrega al actor al día correspondiente
        if nuevo_dataframe.iloc[i, j] == 1:
            dias[j].append(nuevo_dataframe.iloc[i, -1])

# Encuentra el día con el menor número de actores
min_actores = float("inf")
dia_min = -1
for i, dia in enumerate(dias):
    if len(dia) < min_actores:
        min_actores = len(dia)
        dia_min = i

# Imprime el día con el menor número de actores
print("El día con el menor número de actores es el día", dia_min + 1)

El día con el menor número de actores es el día 8

Enumera las referencias que has utilizado(si ha sido necesario) para llevar a cabo el trabajo

Respuesta:

* Algoritmo Floy-Marshall: [link text](https://medium.com/algoritmo-floyd-warshall/algoritmo-de-floyd-warshall-e1fd1a900d8)

* Revisión material visto en clase